GraphEdgeList.o: GraphEdgeList.c
	gcc -g -c GraphEdgeList.c -o GraphEdgeList.o
Main1.o: Main1.c
	gcc -g -c Main1.c -o Main1.o
my1: GraphEdgeList.o Main1.o
	gcc GraphEdgeList.o Main1.o -o my
GraphAdjList.o: GraphAdjList.c
	gcc -g -c GraphAdjList.c -o GraphAdjList.o
Main2.o: Main2.c
	gcc -g -c Main2.c -o Main2.o
my2: GraphAdjList.o Main2.o
	gcc GraphAdjList.o Main2.o -o my2
GAdjLCitation.o: GAdjLCitation.c
	gcc -g -c GAdjLCitation.c -o GAdjLCitation.o
Main3.o: Main3.c
	gcc -g -c Main3.c -o Main3.o
my3: GAdjLCitation.o Main3.o
	gcc GAdjLCitation.o Main3.o -o my3
